apiVersion: v1
kind: Namespace
metadata:
  name: testpmd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer-testpmd
  namespace: testpmd
imagePullSecrets:
- name: deployer-dockercfg-cfzqs
secrets:
- name: deployer-token-tm75w
- name: deployer-dockercfg-cfzqs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployer-privileged-testpmd-rolebinding
  namespace: testpmd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: deployer-testpmd
  namespace: testpmd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployer-anyuid-testpmd-rolebinding
  namespace: testpmd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: deployer-testpmd
  namespace: testpmd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testpmd
    app.kubernetes.io/component: testpmd
    app.kubernetes.io/instance: testpmd
  name: testpmd-rhel
  namespace: testpmd
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: testpmd
  template:
    metadata:
      labels:
        app: testpmd
      annotations:
        k8s.v1.cni.cncf.io/networks: testpmd/sriov-nw-du-test-pmd-e810-ens1f0, testpmd/sriov-nw-du-test-pmd-e810-ens1f1
        irq-load-balancing.crio.io: "disable"
        cpu-load-balancing.crio.io: "disable"
    spec:
      runtimeClassName: "performance-sno-perfprofile"
      serviceAccount: deployer-testpmd
      serviceAccountName: deployer-testpmd
      securityContext:
        runAsUser: 0
        capabilities:
          add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW","NET_ADMIN"]
      containers:
        - image: registry.redhat.io/openshift4/dpdk-base-rhel8
          command:
          - /bin/bash
          - -c
          - sleep INF
          securityContext:
            runAsUser: 0
            capabilities:
              add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW","NET_ADMIN"]
          imagePullPolicy: Always
          env:
            - name: RUN_TYPE
              value: "testpmd"
          name: testpmd
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            limits:
              cpu: "16"
              hugepages-1Gi: 8Gi
              memory: 2Gi
              openshift.io/e810_ens1f0: "1"
              openshift.io/e810_ens1f1: "1"
            requests:
              cpu: "16"
              hugepages-1Gi: 8Gi
              memory: 2Gi
              openshift.io/e810_ens1f0: "1"
              openshift.io/e810_ens1f1: "1"
          volumeMounts:
            - mountPath: /mnt/huge
              name: hugepage
      dnsPolicy: ClusterFirst
      volumes:
      - name: hugepage
        emptyDir:
          medium: HugePages
      restartPolicy: Always
  test: false
